name: Cypress Tests

on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: password=${{ secrets.CYPRESS_PASSWORD }}
          config-file: cypress.config.ts
          wait-on: 'https://stage.foo.redhat.com:1337/beta/ansible/seats-administration'
          build: npm run build
          start: npm run start:stage:beta