name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          HTTPS_PROXY: ${{ secrets.CYPRESS_HTTPS_PROXY }}
          HTTP_PROXY: ${{ secrets.CYPRESS_HTTPS_PROXY }}
        with:
          env: password=${{ secrets.CYPRESS_PASSWORD }}, HTTPS_PROXY= ${{ secrets.CYPRESS_HTTPS_PROXY }}, HTTP_PROXY= ${{ secrets.CYPRESS_HTTPS_PROXY }}
          config-file: cypress.config.ts
          build: npm run build
          start: npm start